"use client";
// GENERATED by scripts/fetch-shadcn-primitives.ts — do not edit by hand.
//
// Style-aware dispatcher: renders shadcn's ACTUAL per-style accordion for the style
// selected in the showcase, so the preview matches what a consumer installs. This
// file is showcase-only — the build never ships it (our components depend on the
// bare @shadcn/accordion, resolved to the consumer's own installed primitive).
import type { ComponentProps } from "react";

import { useShowcaseStyle } from "~/showcase/style-context";
import * as vega from "~/showcase/primitives/vega/accordion";
import * as nova from "~/showcase/primitives/nova/accordion";
import * as maia from "~/showcase/primitives/maia/accordion";
import * as lyra from "~/showcase/primitives/lyra/accordion";
import * as mira from "~/showcase/primitives/mira/accordion";
import * as luma from "~/showcase/primitives/luma/accordion";
import * as sera from "~/showcase/primitives/sera/accordion";
import * as rhea from "~/showcase/primitives/rhea/accordion";

const BY_STYLE: Record<string, typeof mira> = {
  vega,
  nova,
  maia,
  lyra,
  mira,
  luma,
  sera,
  rhea,
};

export function Accordion(props: ComponentProps<typeof mira.Accordion>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.Accordion {...props} />;
}

export function AccordionContent(props: ComponentProps<typeof mira.AccordionContent>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.AccordionContent {...props} />;
}

export function AccordionItem(props: ComponentProps<typeof mira.AccordionItem>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.AccordionItem {...props} />;
}

export function AccordionTrigger(props: ComponentProps<typeof mira.AccordionTrigger>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.AccordionTrigger {...props} />;
}
