"use client";
// GENERATED by scripts/fetch-shadcn-primitives.ts — do not edit by hand.
//
// Style-aware dispatcher: renders shadcn's ACTUAL per-style attachment for the style
// selected in the showcase, so the preview matches what a consumer installs. This
// file is showcase-only — the build never ships it (our components depend on the
// bare @shadcn/attachment, resolved to the consumer's own installed primitive).
import type { ComponentProps } from "react";

import { useShowcaseStyle } from "~/showcase/style-context";
import * as vega from "~/showcase/primitives/vega/attachment";
import * as nova from "~/showcase/primitives/nova/attachment";
import * as maia from "~/showcase/primitives/maia/attachment";
import * as lyra from "~/showcase/primitives/lyra/attachment";
import * as mira from "~/showcase/primitives/mira/attachment";
import * as luma from "~/showcase/primitives/luma/attachment";
import * as sera from "~/showcase/primitives/sera/attachment";
import * as rhea from "~/showcase/primitives/rhea/attachment";

const BY_STYLE: Record<string, typeof mira> = {
  vega,
  nova,
  maia,
  lyra,
  mira,
  luma,
  sera,
  rhea,
};

export function Attachment(props: ComponentProps<typeof mira.Attachment>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.Attachment {...props} />;
}

export function AttachmentAction(props: ComponentProps<typeof mira.AttachmentAction>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.AttachmentAction {...props} />;
}

export function AttachmentActions(props: ComponentProps<typeof mira.AttachmentActions>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.AttachmentActions {...props} />;
}

export function AttachmentContent(props: ComponentProps<typeof mira.AttachmentContent>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.AttachmentContent {...props} />;
}

export function AttachmentDescription(props: ComponentProps<typeof mira.AttachmentDescription>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.AttachmentDescription {...props} />;
}

export function AttachmentGroup(props: ComponentProps<typeof mira.AttachmentGroup>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.AttachmentGroup {...props} />;
}

export function AttachmentMedia(props: ComponentProps<typeof mira.AttachmentMedia>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.AttachmentMedia {...props} />;
}

export function AttachmentTitle(props: ComponentProps<typeof mira.AttachmentTitle>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.AttachmentTitle {...props} />;
}

export function AttachmentTrigger(props: ComponentProps<typeof mira.AttachmentTrigger>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.AttachmentTrigger {...props} />;
}
