"use client";
// GENERATED by scripts/fetch-shadcn-primitives.ts — do not edit by hand.
//
// Style-aware dispatcher: renders shadcn's ACTUAL per-style avatar for the style
// selected in the showcase, so the preview matches what a consumer installs. This
// file is showcase-only — the build never ships it (our components depend on the
// bare @shadcn/avatar, resolved to the consumer's own installed primitive).
import type { ComponentProps } from "react";

import { useShowcaseStyle } from "~/showcase/style-context";
import * as vega from "~/showcase/primitives/vega/avatar";
import * as nova from "~/showcase/primitives/nova/avatar";
import * as maia from "~/showcase/primitives/maia/avatar";
import * as lyra from "~/showcase/primitives/lyra/avatar";
import * as mira from "~/showcase/primitives/mira/avatar";
import * as luma from "~/showcase/primitives/luma/avatar";
import * as sera from "~/showcase/primitives/sera/avatar";
import * as rhea from "~/showcase/primitives/rhea/avatar";

const BY_STYLE: Record<string, typeof mira> = {
  vega,
  nova,
  maia,
  lyra,
  mira,
  luma,
  sera,
  rhea,
};

export function Avatar(props: ComponentProps<typeof mira.Avatar>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.Avatar {...props} />;
}

export function AvatarBadge(props: ComponentProps<typeof mira.AvatarBadge>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.AvatarBadge {...props} />;
}

export function AvatarFallback(props: ComponentProps<typeof mira.AvatarFallback>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.AvatarFallback {...props} />;
}

export function AvatarGroup(props: ComponentProps<typeof mira.AvatarGroup>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.AvatarGroup {...props} />;
}

export function AvatarGroupCount(props: ComponentProps<typeof mira.AvatarGroupCount>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.AvatarGroupCount {...props} />;
}

export function AvatarImage(props: ComponentProps<typeof mira.AvatarImage>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.AvatarImage {...props} />;
}
