"use client";
// GENERATED by scripts/fetch-shadcn-primitives.ts — do not edit by hand.
//
// Style-aware dispatcher: renders shadcn's ACTUAL per-style button for the style
// selected in the showcase, so the preview matches what a consumer installs. This
// file is showcase-only — the build never ships it (our components depend on the
// bare @shadcn/button, resolved to the consumer's own installed primitive).
import type { ComponentProps } from "react";

import { useShowcaseStyle } from "~/showcase/style-context";
import * as vega from "~/showcase/primitives/vega/button";
import * as nova from "~/showcase/primitives/nova/button";
import * as maia from "~/showcase/primitives/maia/button";
import * as lyra from "~/showcase/primitives/lyra/button";
import * as mira from "~/showcase/primitives/mira/button";
import * as luma from "~/showcase/primitives/luma/button";
import * as sera from "~/showcase/primitives/sera/button";
import * as rhea from "~/showcase/primitives/rhea/button";

const BY_STYLE: Record<string, typeof mira> = {
  vega,
  nova,
  maia,
  lyra,
  mira,
  luma,
  sera,
  rhea,
};

export function Button(props: ComponentProps<typeof mira.Button>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.Button {...props} />;
}
