"use client";
// GENERATED by scripts/fetch-shadcn-primitives.ts — do not edit by hand.
//
// Style-aware dispatcher: renders shadcn's ACTUAL per-style button-group for the style
// selected in the showcase, so the preview matches what a consumer installs. This
// file is showcase-only — the build never ships it (our components depend on the
// bare @shadcn/button-group, resolved to the consumer's own installed primitive).
import type { ComponentProps } from "react";

import { useShowcaseStyle } from "~/showcase/style-context";
import * as vega from "~/showcase/primitives/vega/button-group";
import * as nova from "~/showcase/primitives/nova/button-group";
import * as maia from "~/showcase/primitives/maia/button-group";
import * as lyra from "~/showcase/primitives/lyra/button-group";
import * as mira from "~/showcase/primitives/mira/button-group";
import * as luma from "~/showcase/primitives/luma/button-group";
import * as sera from "~/showcase/primitives/sera/button-group";
import * as rhea from "~/showcase/primitives/rhea/button-group";

const BY_STYLE: Record<string, typeof mira> = {
  vega,
  nova,
  maia,
  lyra,
  mira,
  luma,
  sera,
  rhea,
};

export function ButtonGroup(props: ComponentProps<typeof mira.ButtonGroup>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.ButtonGroup {...props} />;
}

export function ButtonGroupSeparator(props: ComponentProps<typeof mira.ButtonGroupSeparator>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.ButtonGroupSeparator {...props} />;
}

export function ButtonGroupText(props: ComponentProps<typeof mira.ButtonGroupText>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.ButtonGroupText {...props} />;
}
