"use client";
// GENERATED by scripts/fetch-shadcn-primitives.ts — do not edit by hand.
//
// Style-aware dispatcher: renders shadcn's ACTUAL per-style card for the style
// selected in the showcase, so the preview matches what a consumer installs. This
// file is showcase-only — the build never ships it (our components depend on the
// bare @shadcn/card, resolved to the consumer's own installed primitive).
import type { ComponentProps } from "react";

import { useShowcaseStyle } from "~/showcase/style-context";
import * as vega from "~/showcase/primitives/vega/card";
import * as nova from "~/showcase/primitives/nova/card";
import * as maia from "~/showcase/primitives/maia/card";
import * as lyra from "~/showcase/primitives/lyra/card";
import * as mira from "~/showcase/primitives/mira/card";
import * as luma from "~/showcase/primitives/luma/card";
import * as sera from "~/showcase/primitives/sera/card";
import * as rhea from "~/showcase/primitives/rhea/card";

const BY_STYLE: Record<string, typeof mira> = {
  vega,
  nova,
  maia,
  lyra,
  mira,
  luma,
  sera,
  rhea,
};

export function Card(props: ComponentProps<typeof mira.Card>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.Card {...props} />;
}

export function CardAction(props: ComponentProps<typeof mira.CardAction>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.CardAction {...props} />;
}

export function CardContent(props: ComponentProps<typeof mira.CardContent>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.CardContent {...props} />;
}

export function CardDescription(props: ComponentProps<typeof mira.CardDescription>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.CardDescription {...props} />;
}

export function CardFooter(props: ComponentProps<typeof mira.CardFooter>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.CardFooter {...props} />;
}

export function CardHeader(props: ComponentProps<typeof mira.CardHeader>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.CardHeader {...props} />;
}

export function CardTitle(props: ComponentProps<typeof mira.CardTitle>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.CardTitle {...props} />;
}
