"use client";
// GENERATED by scripts/fetch-shadcn-primitives.ts — do not edit by hand.
//
// Style-aware dispatcher: renders shadcn's ACTUAL per-style checkbox for the style
// selected in the showcase, so the preview matches what a consumer installs. This
// file is showcase-only — the build never ships it (our components depend on the
// bare @shadcn/checkbox, resolved to the consumer's own installed primitive).
import type { ComponentProps } from "react";

import { useShowcaseStyle } from "~/showcase/style-context";
import * as vega from "~/showcase/primitives/vega/checkbox";
import * as nova from "~/showcase/primitives/nova/checkbox";
import * as maia from "~/showcase/primitives/maia/checkbox";
import * as lyra from "~/showcase/primitives/lyra/checkbox";
import * as mira from "~/showcase/primitives/mira/checkbox";
import * as luma from "~/showcase/primitives/luma/checkbox";
import * as sera from "~/showcase/primitives/sera/checkbox";
import * as rhea from "~/showcase/primitives/rhea/checkbox";

const BY_STYLE: Record<string, typeof mira> = {
  vega,
  nova,
  maia,
  lyra,
  mira,
  luma,
  sera,
  rhea,
};

export function Checkbox(props: ComponentProps<typeof mira.Checkbox>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.Checkbox {...props} />;
}
