"use client";
// GENERATED by scripts/fetch-shadcn-primitives.ts — do not edit by hand.
//
// Style-aware dispatcher: renders shadcn's ACTUAL per-style command for the style
// selected in the showcase, so the preview matches what a consumer installs. This
// file is showcase-only — the build never ships it (our components depend on the
// bare @shadcn/command, resolved to the consumer's own installed primitive).
import type { ComponentProps } from "react";

import { useShowcaseStyle } from "~/showcase/style-context";
import * as vega from "~/showcase/primitives/vega/command";
import * as nova from "~/showcase/primitives/nova/command";
import * as maia from "~/showcase/primitives/maia/command";
import * as lyra from "~/showcase/primitives/lyra/command";
import * as mira from "~/showcase/primitives/mira/command";
import * as luma from "~/showcase/primitives/luma/command";
import * as sera from "~/showcase/primitives/sera/command";
import * as rhea from "~/showcase/primitives/rhea/command";

const BY_STYLE: Record<string, typeof mira> = {
  vega,
  nova,
  maia,
  lyra,
  mira,
  luma,
  sera,
  rhea,
};

export function Command(props: ComponentProps<typeof mira.Command>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.Command {...props} />;
}

export function CommandDialog(props: ComponentProps<typeof mira.CommandDialog>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.CommandDialog {...props} />;
}

export function CommandEmpty(props: ComponentProps<typeof mira.CommandEmpty>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.CommandEmpty {...props} />;
}

export function CommandGroup(props: ComponentProps<typeof mira.CommandGroup>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.CommandGroup {...props} />;
}

export function CommandInput(props: ComponentProps<typeof mira.CommandInput>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.CommandInput {...props} />;
}

export function CommandItem(props: ComponentProps<typeof mira.CommandItem>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.CommandItem {...props} />;
}

export function CommandList(props: ComponentProps<typeof mira.CommandList>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.CommandList {...props} />;
}

export function CommandSeparator(props: ComponentProps<typeof mira.CommandSeparator>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.CommandSeparator {...props} />;
}

export function CommandShortcut(props: ComponentProps<typeof mira.CommandShortcut>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.CommandShortcut {...props} />;
}
