"use client";
// GENERATED by scripts/fetch-shadcn-primitives.ts — do not edit by hand.
//
// Style-aware dispatcher: renders shadcn's ACTUAL per-style dialog for the style
// selected in the showcase, so the preview matches what a consumer installs. This
// file is showcase-only — the build never ships it (our components depend on the
// bare @shadcn/dialog, resolved to the consumer's own installed primitive).
import type { ComponentProps } from "react";

import { useShowcaseStyle } from "~/showcase/style-context";
import * as vega from "~/showcase/primitives/vega/dialog";
import * as nova from "~/showcase/primitives/nova/dialog";
import * as maia from "~/showcase/primitives/maia/dialog";
import * as lyra from "~/showcase/primitives/lyra/dialog";
import * as mira from "~/showcase/primitives/mira/dialog";
import * as luma from "~/showcase/primitives/luma/dialog";
import * as sera from "~/showcase/primitives/sera/dialog";
import * as rhea from "~/showcase/primitives/rhea/dialog";

const BY_STYLE: Record<string, typeof mira> = {
  vega,
  nova,
  maia,
  lyra,
  mira,
  luma,
  sera,
  rhea,
};

export function Dialog(props: ComponentProps<typeof mira.Dialog>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.Dialog {...props} />;
}

export function DialogClose(props: ComponentProps<typeof mira.DialogClose>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.DialogClose {...props} />;
}

export function DialogContent(props: ComponentProps<typeof mira.DialogContent>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.DialogContent {...props} />;
}

export function DialogDescription(props: ComponentProps<typeof mira.DialogDescription>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.DialogDescription {...props} />;
}

export function DialogFooter(props: ComponentProps<typeof mira.DialogFooter>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.DialogFooter {...props} />;
}

export function DialogHeader(props: ComponentProps<typeof mira.DialogHeader>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.DialogHeader {...props} />;
}

export function DialogOverlay(props: ComponentProps<typeof mira.DialogOverlay>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.DialogOverlay {...props} />;
}

export function DialogPortal(props: ComponentProps<typeof mira.DialogPortal>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.DialogPortal {...props} />;
}

export function DialogTitle(props: ComponentProps<typeof mira.DialogTitle>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.DialogTitle {...props} />;
}

export function DialogTrigger(props: ComponentProps<typeof mira.DialogTrigger>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.DialogTrigger {...props} />;
}
