"use client";
// GENERATED by scripts/fetch-shadcn-primitives.ts — do not edit by hand.
//
// Style-aware dispatcher: renders shadcn's ACTUAL per-style field for the style
// selected in the showcase, so the preview matches what a consumer installs. This
// file is showcase-only — the build never ships it (our components depend on the
// bare @shadcn/field, resolved to the consumer's own installed primitive).
import type { ComponentProps } from "react";

import { useShowcaseStyle } from "~/showcase/style-context";
import * as vega from "~/showcase/primitives/vega/field";
import * as nova from "~/showcase/primitives/nova/field";
import * as maia from "~/showcase/primitives/maia/field";
import * as lyra from "~/showcase/primitives/lyra/field";
import * as mira from "~/showcase/primitives/mira/field";
import * as luma from "~/showcase/primitives/luma/field";
import * as sera from "~/showcase/primitives/sera/field";
import * as rhea from "~/showcase/primitives/rhea/field";

const BY_STYLE: Record<string, typeof mira> = {
  vega,
  nova,
  maia,
  lyra,
  mira,
  luma,
  sera,
  rhea,
};

export function Field(props: ComponentProps<typeof mira.Field>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.Field {...props} />;
}

export function FieldContent(props: ComponentProps<typeof mira.FieldContent>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.FieldContent {...props} />;
}

export function FieldDescription(props: ComponentProps<typeof mira.FieldDescription>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.FieldDescription {...props} />;
}

export function FieldError(props: ComponentProps<typeof mira.FieldError>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.FieldError {...props} />;
}

export function FieldGroup(props: ComponentProps<typeof mira.FieldGroup>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.FieldGroup {...props} />;
}

export function FieldLabel(props: ComponentProps<typeof mira.FieldLabel>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.FieldLabel {...props} />;
}

export function FieldLegend(props: ComponentProps<typeof mira.FieldLegend>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.FieldLegend {...props} />;
}

export function FieldSeparator(props: ComponentProps<typeof mira.FieldSeparator>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.FieldSeparator {...props} />;
}

export function FieldSet(props: ComponentProps<typeof mira.FieldSet>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.FieldSet {...props} />;
}

export function FieldTitle(props: ComponentProps<typeof mira.FieldTitle>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.FieldTitle {...props} />;
}
