"use client";
// GENERATED by scripts/fetch-shadcn-primitives.ts — do not edit by hand.
//
// Style-aware dispatcher: renders shadcn's ACTUAL per-style item for the style
// selected in the showcase, so the preview matches what a consumer installs. This
// file is showcase-only — the build never ships it (our components depend on the
// bare @shadcn/item, resolved to the consumer's own installed primitive).
import type { ComponentProps } from "react";

import { useShowcaseStyle } from "~/showcase/style-context";
import * as vega from "~/showcase/primitives/vega/item";
import * as nova from "~/showcase/primitives/nova/item";
import * as maia from "~/showcase/primitives/maia/item";
import * as lyra from "~/showcase/primitives/lyra/item";
import * as mira from "~/showcase/primitives/mira/item";
import * as luma from "~/showcase/primitives/luma/item";
import * as sera from "~/showcase/primitives/sera/item";
import * as rhea from "~/showcase/primitives/rhea/item";

const BY_STYLE: Record<string, typeof mira> = {
  vega,
  nova,
  maia,
  lyra,
  mira,
  luma,
  sera,
  rhea,
};

export function Item(props: ComponentProps<typeof mira.Item>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.Item {...props} />;
}

export function ItemActions(props: ComponentProps<typeof mira.ItemActions>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.ItemActions {...props} />;
}

export function ItemContent(props: ComponentProps<typeof mira.ItemContent>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.ItemContent {...props} />;
}

export function ItemDescription(props: ComponentProps<typeof mira.ItemDescription>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.ItemDescription {...props} />;
}

export function ItemFooter(props: ComponentProps<typeof mira.ItemFooter>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.ItemFooter {...props} />;
}

export function ItemGroup(props: ComponentProps<typeof mira.ItemGroup>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.ItemGroup {...props} />;
}

export function ItemHeader(props: ComponentProps<typeof mira.ItemHeader>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.ItemHeader {...props} />;
}

export function ItemMedia(props: ComponentProps<typeof mira.ItemMedia>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.ItemMedia {...props} />;
}

export function ItemSeparator(props: ComponentProps<typeof mira.ItemSeparator>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.ItemSeparator {...props} />;
}

export function ItemTitle(props: ComponentProps<typeof mira.ItemTitle>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.ItemTitle {...props} />;
}
