"use client";
// GENERATED by scripts/fetch-shadcn-primitives.ts — do not edit by hand.
//
// Style-aware dispatcher: renders shadcn's ACTUAL per-style popover for the style
// selected in the showcase, so the preview matches what a consumer installs. This
// file is showcase-only — the build never ships it (our components depend on the
// bare @shadcn/popover, resolved to the consumer's own installed primitive).
import type { ComponentProps } from "react";

import { useShowcaseStyle } from "~/showcase/style-context";
import * as vega from "~/showcase/primitives/vega/popover";
import * as nova from "~/showcase/primitives/nova/popover";
import * as maia from "~/showcase/primitives/maia/popover";
import * as lyra from "~/showcase/primitives/lyra/popover";
import * as mira from "~/showcase/primitives/mira/popover";
import * as luma from "~/showcase/primitives/luma/popover";
import * as sera from "~/showcase/primitives/sera/popover";
import * as rhea from "~/showcase/primitives/rhea/popover";

const BY_STYLE: Record<string, typeof mira> = {
  vega,
  nova,
  maia,
  lyra,
  mira,
  luma,
  sera,
  rhea,
};

export function Popover(props: ComponentProps<typeof mira.Popover>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.Popover {...props} />;
}

export function PopoverContent(props: ComponentProps<typeof mira.PopoverContent>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.PopoverContent {...props} />;
}

export function PopoverDescription(props: ComponentProps<typeof mira.PopoverDescription>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.PopoverDescription {...props} />;
}

export function PopoverHeader(props: ComponentProps<typeof mira.PopoverHeader>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.PopoverHeader {...props} />;
}

export function PopoverTitle(props: ComponentProps<typeof mira.PopoverTitle>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.PopoverTitle {...props} />;
}

export function PopoverTrigger(props: ComponentProps<typeof mira.PopoverTrigger>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.PopoverTrigger {...props} />;
}
