"use client";
// GENERATED by scripts/fetch-shadcn-primitives.ts — do not edit by hand.
//
// Style-aware dispatcher: renders shadcn's ACTUAL per-style switch for the style
// selected in the showcase, so the preview matches what a consumer installs. This
// file is showcase-only — the build never ships it (our components depend on the
// bare @shadcn/switch, resolved to the consumer's own installed primitive).
import type { ComponentProps } from "react";

import { useShowcaseStyle } from "~/showcase/style-context";
import * as vega from "~/showcase/primitives/vega/switch";
import * as nova from "~/showcase/primitives/nova/switch";
import * as maia from "~/showcase/primitives/maia/switch";
import * as lyra from "~/showcase/primitives/lyra/switch";
import * as mira from "~/showcase/primitives/mira/switch";
import * as luma from "~/showcase/primitives/luma/switch";
import * as sera from "~/showcase/primitives/sera/switch";
import * as rhea from "~/showcase/primitives/rhea/switch";

const BY_STYLE: Record<string, typeof mira> = {
  vega,
  nova,
  maia,
  lyra,
  mira,
  luma,
  sera,
  rhea,
};

export function Switch(props: ComponentProps<typeof mira.Switch>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.Switch {...props} />;
}
