"use client";
// GENERATED by scripts/fetch-shadcn-primitives.ts — do not edit by hand.
//
// Style-aware dispatcher: renders shadcn's ACTUAL per-style tabs for the style
// selected in the showcase, so the preview matches what a consumer installs. This
// file is showcase-only — the build never ships it (our components depend on the
// bare @shadcn/tabs, resolved to the consumer's own installed primitive).
import type { ComponentProps } from "react";

import { useShowcaseStyle } from "~/showcase/style-context";
import * as vega from "~/showcase/primitives/vega/tabs";
import * as nova from "~/showcase/primitives/nova/tabs";
import * as maia from "~/showcase/primitives/maia/tabs";
import * as lyra from "~/showcase/primitives/lyra/tabs";
import * as mira from "~/showcase/primitives/mira/tabs";
import * as luma from "~/showcase/primitives/luma/tabs";
import * as sera from "~/showcase/primitives/sera/tabs";
import * as rhea from "~/showcase/primitives/rhea/tabs";

const BY_STYLE: Record<string, typeof mira> = {
  vega,
  nova,
  maia,
  lyra,
  mira,
  luma,
  sera,
  rhea,
};

export function Tabs(props: ComponentProps<typeof mira.Tabs>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.Tabs {...props} />;
}

export function TabsContent(props: ComponentProps<typeof mira.TabsContent>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.TabsContent {...props} />;
}

export function TabsList(props: ComponentProps<typeof mira.TabsList>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.TabsList {...props} />;
}

export function TabsTrigger(props: ComponentProps<typeof mira.TabsTrigger>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.TabsTrigger {...props} />;
}
