"use client";
// GENERATED by scripts/fetch-shadcn-primitives.ts — do not edit by hand.
//
// Style-aware dispatcher: renders shadcn's ACTUAL per-style textarea for the style
// selected in the showcase, so the preview matches what a consumer installs. This
// file is showcase-only — the build never ships it (our components depend on the
// bare @shadcn/textarea, resolved to the consumer's own installed primitive).
import type { ComponentProps } from "react";

import { useShowcaseStyle } from "~/showcase/style-context";
import * as vega from "~/showcase/primitives/vega/textarea";
import * as nova from "~/showcase/primitives/nova/textarea";
import * as maia from "~/showcase/primitives/maia/textarea";
import * as lyra from "~/showcase/primitives/lyra/textarea";
import * as mira from "~/showcase/primitives/mira/textarea";
import * as luma from "~/showcase/primitives/luma/textarea";
import * as sera from "~/showcase/primitives/sera/textarea";
import * as rhea from "~/showcase/primitives/rhea/textarea";

const BY_STYLE: Record<string, typeof mira> = {
  vega,
  nova,
  maia,
  lyra,
  mira,
  luma,
  sera,
  rhea,
};

export function Textarea(props: ComponentProps<typeof mira.Textarea>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.Textarea {...props} />;
}
