"use client";
// GENERATED by scripts/fetch-shadcn-primitives.ts — do not edit by hand.
//
// Style-aware dispatcher: renders shadcn's ACTUAL per-style toggle for the style
// selected in the showcase, so the preview matches what a consumer installs. This
// file is showcase-only — the build never ships it (our components depend on the
// bare @shadcn/toggle, resolved to the consumer's own installed primitive).
import type { ComponentProps } from "react";

import { useShowcaseStyle } from "~/showcase/style-context";
import * as vega from "~/showcase/primitives/vega/toggle";
import * as nova from "~/showcase/primitives/nova/toggle";
import * as maia from "~/showcase/primitives/maia/toggle";
import * as lyra from "~/showcase/primitives/lyra/toggle";
import * as mira from "~/showcase/primitives/mira/toggle";
import * as luma from "~/showcase/primitives/luma/toggle";
import * as sera from "~/showcase/primitives/sera/toggle";
import * as rhea from "~/showcase/primitives/rhea/toggle";

const BY_STYLE: Record<string, typeof mira> = {
  vega,
  nova,
  maia,
  lyra,
  mira,
  luma,
  sera,
  rhea,
};

export function Toggle(props: ComponentProps<typeof mira.Toggle>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.Toggle {...props} />;
}
