"use client";
// GENERATED by scripts/fetch-shadcn-primitives.ts — do not edit by hand.
//
// Style-aware dispatcher: renders shadcn's ACTUAL per-style tooltip for the style
// selected in the showcase, so the preview matches what a consumer installs. This
// file is showcase-only — the build never ships it (our components depend on the
// bare @shadcn/tooltip, resolved to the consumer's own installed primitive).
import type { ComponentProps } from "react";

import { useShowcaseStyle } from "~/showcase/style-context";
import * as vega from "~/showcase/primitives/vega/tooltip";
import * as nova from "~/showcase/primitives/nova/tooltip";
import * as maia from "~/showcase/primitives/maia/tooltip";
import * as lyra from "~/showcase/primitives/lyra/tooltip";
import * as mira from "~/showcase/primitives/mira/tooltip";
import * as luma from "~/showcase/primitives/luma/tooltip";
import * as sera from "~/showcase/primitives/sera/tooltip";
import * as rhea from "~/showcase/primitives/rhea/tooltip";

const BY_STYLE: Record<string, typeof mira> = {
  vega,
  nova,
  maia,
  lyra,
  mira,
  luma,
  sera,
  rhea,
};

export function Tooltip(props: ComponentProps<typeof mira.Tooltip>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.Tooltip {...props} />;
}

export function TooltipContent(props: ComponentProps<typeof mira.TooltipContent>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.TooltipContent {...props} />;
}

export function TooltipProvider(props: ComponentProps<typeof mira.TooltipProvider>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.TooltipProvider {...props} />;
}

export function TooltipTrigger(props: ComponentProps<typeof mira.TooltipTrigger>) {
  const s = (BY_STYLE[useShowcaseStyle()] ?? mira) as typeof mira;
  return <s.TooltipTrigger {...props} />;
}
