/**
 * Extracts the object key from a public storage URL for the given bucket.
 * Handles both Supabase's public-object URL shape and R2's
 * `${R2_PUBLIC_URL}/${bucket}/${key}` shape, since a medium's URL may have
 * been generated by either provider depending on when it was uploaded.
 */
export function getFileKeyFromPublicUrl(
  publicUrl: string,
  bucket: string,
): string | null {
  const supabasePattern = new RegExp(
    `/storage/v1/object/public/${bucket}/(.+)$`,
  );
  const supabaseMatch = publicUrl.match(supabasePattern);
  if (supabaseMatch) return supabaseMatch[1];

  const r2PublicUrl = process.env.R2_PUBLIC_URL;
  if (r2PublicUrl) {
    const r2Prefix = `${r2PublicUrl}/${bucket}/`;
    if (publicUrl.startsWith(r2Prefix)) {
      const key = publicUrl.slice(r2Prefix.length);
      return key || null;
    }
  }

  return null;
}
